DO WHILE INKEY$ = ""
CLS
COLOR INT(RND * 14 + 1)
RANDA = INT(RND * 9 + 1)
RANDB = INT(RND * 71 + 1)
LOCATE RANDA, RANDB
PRINT "ษหอออออออออหอออออออออหป"
RANDA = RANDA + 1
LOCATE RANDA, RANDB
PRINT "บฬอหอออออออสอออออออหอนบ"
RANDA = RANDA + 1
LOCATE RANDA, RANDB
PRINT "บบษสอออออออัอออออออสปบบ"
RANDA = RANDA + 1
LOCATE RANDA, RANDB
PRINT "บฬน  ฺฤฤฤฤฤมฤฤฤฤฤฟ  ฬนบ"
RANDA = RANDA + 1
LOCATE RANDA, RANDB
PRINT "บบบฺฤู           ภฤฟบบบ"
RANDA = RANDA + 1
LOCATE RANDA, RANDB
PRINT "บบบณ   XENOPHOBE   ณบบบ"
RANDA = RANDA + 1
LOCATE RANDA, RANDB
PRINT "บบบณ  ENTERPRISES  ณบบบ"
RANDA = RANDA + 1
LOCATE RANDA, RANDB
PRINT "ฬนวด      INC.     รถฬน"
RANDA = RANDA + 1
LOCATE RANDA, RANDB
PRINT "บบบณ  E-Mail me at ณบบบ"
RANDA = RANDA + 1
LOCATE RANDA, RANDB
PRINT "บบบณ   XENOPHOBEI  ณบบบ"
RANDA = RANDA + 1
LOCATE RANDA, RANDB
PRINT "บบบภฤฟ  @AOL.COM ฺฤูบบบ"
RANDA = RANDA + 1
LOCATE RANDA, RANDB
PRINT "บฬน  ภฤฤฤฤฤยฤฤฤฤฤู  ฬนบ"
RANDA = RANDA + 1
LOCATE RANDA, RANDB
PRINT "บบศหอออออออฯอออออออหผบบ"
RANDA = RANDA + 1
LOCATE RANDA, RANDB
PRINT "บฬอสอออออออหอออออออสอนบ"
RANDA = RANDA + 1
LOCATE RANDA, RANDB
PRINT "ศสอออออออออสอออออออออสผ"
RANDA = RANDA + 1
SLEEP 1
LOOP
COLOR 7

