' HOW TO USE SUBROUTINES
' IRV'S VERSION

' When a qbasic program contains subroutines, all of the coding is in
' one big file, except that you can only see the main program or one
' subroutine on the screen at one time. 


'TO CREATE A PROGRAM WITH SUBROUTINES

' 1. Menu-select FILE and NEW.
' 2. Enter a short program to be called AA (for example).
' 3. Menu-select EDIT and NEW-SUB.
' 4. Enter SUB coding for subroutine BB.
' 5. Menu-select EDIT and NEW-SUB.
' 6. Enter SUB coding for subroutine CC.
' 7. Repeat 5 and 6 for each added subroutine.
' 8. Menu-select FILE and SAVE and save as AA.BAS, and
'    now you have a main program AA and subroutines BB, CC, etc.

'TO DISPLAY OR EDIT A PROGRAM CONTAINING SUBROUTINES
' 1. Menu-select FILE and OPEN.
' 2. Click on the displayed name of the main program to edit.
' 3. To see and/or edit a subroutine of that program,
'    menu-select EDIT and SUBs.
'    then click on the displayed name of the desired subroutine.
' 4. To see the main program, menu-select VIEW and SUBs again
'    and click on the displayed name of the main program.

'TO ALTER THE CODING
'   You can delete a subroutine by menu-selecting
'   VIEW and SUBs, then click on displayed name, then select DELETE.
'   You can add a subroutine by menu-selecting EDIT and NEW-SUB.
'   You can alter the coding by using the editor or other keyboard tricks.
'   If you want to use a previously-written subroutine, use the EDIT
'   COPY and PASTE to copy it into your program.



